site_name: mysql-notebook

# readthedocs   material
theme:  readthedocs
use_directory_urls: true

docs_dir: 'docs'


pages:
- 首页: 'index.md'

- 开发技巧:
  - 正确使用join从句: 'jq/1.md'
  - 与join相关的SQL技巧: 'jq/2.md'
  - 行列相互转化的SQL技巧: 'jq/3.md'
  - 利用主键删除重复数据的SQL技巧: 'jq/4.md'
  - 子查询中实现多列过滤的SQL技巧: 'jq/5.md'
  - 同一属性的多值过滤的SQL技巧: 'jq/6.md'



- 性能优化:
  - 影响数据库性能几个方面: 'yh/1.md'
  - 存储引擎: 'yh/2.md'
  - 索引优化: 'yh/3.md'
  - SQL查询优化: 'yh/4.md'
  - 分库分表: 'yh/5.md'
  - 事务: 'yh/6.md'
  - 慢查询的开启和分析: 'yh/7.md'






# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/hightfly01/Msql-notebook'


# Copyright
copyright: 'Copyright (c) 2018 hightfly'


extra:
  palette:
    primary: 'blue grey'
    accent: 'blue grey'
  author:
    github: 'hightfly01'


# Extensions
markdown_extensions:
  #高亮
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'
