site_name: mysql-notebook

# readthedocs   material
theme:  material
use_directory_urls: true

docs_dir: 'docs'


pages:
- 首页: 'index.md'

- 正确使用join从句: 'sports-acrobatics.md'
- 与join相关的SQL技巧: 'sql-join-jq.md'
- 行列相互转化的SQL技巧: 'h_and_l_zh.md'
- 利用主键删除重复数据的SQL技巧: 'delete_data_by_id.md'

- 优化: 'performance-optimization.md'



# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/hightfly01/Msql-notebook'


# Copyright
copyright: 'Copyright (c) 2018 hightfly'


extra:
  palette:
    primary: 'blue grey'
    accent: 'blue grey'
  author:
    github: 'hightfly01'


# Extensions
markdown_extensions:
  #高亮
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'
